# only run when we push changes to master or  PRs
on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:
    branches: [master]

env:
  # GitHub Container Registry hostname
  GCR_HOSTNAME: ghcr.io

jobs:
  build_with_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the first stage (build environment)
        uses: docker/build-push-action@v1
        env:
          # use BuildKit to speed up builds and improve caching
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          registry: ${{ env.GCR_HOSTNAME }}
          repository: ${{ github.repository }}
          target: build
          tags: build
          build_args: BUILDKIT_INLINE_CACHE=1
          cache_froms: ${{ env.GCR_HOSTNAME }}/${{ github.repository }}:build

      - name: Build the final product (live artifact)
        uses: docker/build-push-action@v1
        env:
          # use BuildKit to speed up builds and improve caching
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          registry: ${{ env.GCR_HOSTNAME }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          build_args: BUILDKIT_INLINE_CACHE=1
          cache_froms: >
            ${{ env.GCR_HOSTNAME }}/${{ github.repository }}:build,
            ${{ env.GCR_HOSTNAME }}/${{ github.repository }}:latest
