# only run when we push changes to master or PRs
on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:
    branches: [master]

env:
  # GitHub Container Registry hostname
  GCR_HOSTNAME: ghcr.io

jobs:
  build_with_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Craft a valid tag for this build
        id: craft_tag
        run: >
          echo -n "::set-output name=image_tag::";
          echo ${{ github.ref }}
          | sed -E -e 's/refs\/(heads|tags)?\/?//'
          -e 's/\//-/g'
          -e 's/master/latest/'

      - name: Build with cache
        uses: docker/build-push-action@v1
        env:
          # use BuildKit to speed up builds and improve caching
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ${{ env.GPR_HOSTNAME }}
          repository: ${{ github.repository }}/slim
          tags: ${{ steps.craft_tag.outputs.image_tag }}
          build_args: BUILDKIT_INLINE_CACHE=1
          cache_froms: >
            ${{ env.GPR_HOSTNAME }}/${{ github.repository }}:latest,
            ${{ env.GPR_HOSTNAME }}/${{ github.repository }}:${{ steps.craft_tag.outputs.image_tag }}
