# only run when we push changes to master or  PRs
on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      tag:
        description: Build a container image for this GitHub tag
        required: true

env:
  # GitHub Container Registry hostname
  GCR_HOSTNAME: ghcr.io

jobs:
  build_with_action:
    runs-on: ubuntu-latest
    steps:
      # do the normal checkout when the event is push/pull_request
      - uses: actions/checkout@v2
        if: github.event_name != 'workflow_dispatch'

      # checkout the specified tag when the event is workflow_dispatch
      - uses: actions/checkout@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Build and cache first build stage
        # update the first stage cache only when pushing to or tagging main
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v1
        env:
          # use BuildKit to speed up builds and improve caching
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          registry: ${{ env.GCR_HOSTNAME }}
          repository: ${{ github.repository }}
          target: build
          tags: build
          build_args: BUILDKIT_INLINE_CACHE=1
          cache_froms: ${{ env.GCR_HOSTNAME }}/${{ github.repository }}:build

      - name: Build the container image
        uses: docker/build-push-action@v1
        env:
          # use BuildKit to speed up builds and improve caching
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          registry: ${{ env.GCR_HOSTNAME }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          build_args: BUILDKIT_INLINE_CACHE=1
          cache_froms: >
            ${{ env.GCR_HOSTNAME }}/${{ github.repository }}:build,
            ${{ env.GCR_HOSTNAME }}/${{ github.repository }}:latest
